cus:
  user: suyongming
  password: 476231418


eureka:
  client:
    serviceUrl:
      defaultZone: http://${cus.user}:${cus.password}@localhost:8761/eureka

server:
  port: 8787
spring:
  application:
    name: market-cv

ali:
  accessKeyID: LTAIPXQuxFJ7477m
  accessKeySecret: cUW4bir9z0pBJX05g3ozMytBiVSgWt