server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://suyongming:476231418@${eureka.instance.hostname}:${server.port}/eureka/


spring:
  security:
    user:
      roles: SUPERUSER
      name: suyongming
      password: 476231418

#Spring Boot 升级到2.1.3 Cloud 升级至 Finchley.SR1后需要验证csrf  否则client会找不到服务